global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ["gateway:8000"]
  - job_name: ingestion
    static_configs:
      - targets: ["ingestion:8001"]
  - job_name: feature
    static_configs:
      - targets: ["feature-service:8002"]
  - job_name: orchestrator
    static_configs:
      - targets: ["orchestrator:8003"]
  - job_name: rules
    static_configs:
      - targets: ["rules-engine:8004"]
  - job_name: alerts
    static_configs:
      - targets: ["alert-service:8005"]
